#!/usr/bin/env bash

set -e

JETTY_HOME=${1}

REALPATH=$(python -c "import os; print os.path.realpath('${0}')")
PROJECT_ROOT=$(dirname $(dirname ${REALPATH}))

# Copies the client code to Jetty's webapps dir.
DEST=${JETTY_HOME}/webapps/ROOT
[[ -e ${DEST} ]] && rm -rf ${DEST}
cp -r ${PROJECT_ROOT}/client/ ${JETTY_HOME}/webapps/ROOT

# Disables the demo apps, if any.
[[ -e ${JETTY_HOME}/start.d/900-demo.ini ]] && \
    rm ${JETTY_HOME}/start.d/900-demo.ini

# Restarts Jetty.
${JETTY_HOME}/bin/jetty.sh stop
JAVA_OPTIONS="-Dsolr.solr.home=${PROJECT_ROOT}/solr/home ${JAVA_OPTIONS}" \
    ${JETTY_HOME}/bin/jetty.sh start
